#!/bin/bash
set -e

# Generate temporary public and private key for node

# Make sure the node name is given
if [ -z "${1}" ]
then
	echo "Missing the node name" >&2
	exit 1
fi

# Get the name of the script dir
scriptdir="$(readlink -f "$(dirname "${0}")")"

# Create temp dir
temp="$(mktemp --directory)"

# Generate 2048 bit RSA key into the temp dir
ssh-keygen \
	-b '2048' \
	-t 'rsa' \
	-N '' \
	-C "Temporary key generated by $(whoami)@$(hostname --fqdn) at $(date --utc '+%Y-%m-%d %H:%M:%S %Z')" \
	-f "${temp}/rsa"

# Create the directory for the key
mkdir --parents \
	"${scriptdir}/${1}"

# Move the keys
mv "${temp}/rsa.pub" "${scriptdir}/${1}/public"
mv "${temp}/rsa" "${scriptdir}/${1}/secret"

# Remove the temp
rm --recursive --force "${temp}"

echo "Keys stored into ${scriptdir}/${1}"
